### ISSUE TITLE
issue while running node

### ISSUE THREAD

**Issue by manikandtan-ck** [jainanshul/caltech-pedestrian-dataset-extractor#6]
while running node caltech_pd.js
I get the following error:

_Error: Cannot find module 'fs-ext'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\caltech\caltech_pd.js:3:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
_

I tried npm install -g fs-ext 
but I am getting a EACCESS error.

_npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "fs-ext"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! syscall connect

npm ERR! Error: connect EACCES 103.245.222.162:443
npm ERR!     at Object.exports._errnoException (util.js:893:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:916:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1075:14)
npm ERR!  { [Error: connect EACCES 103.245.222.162:443]
npm ERR!   code: 'EACCES',
npm ERR!   errno: 'EACCES',
npm ERR!   syscall: 'connect',
npm ERR!   address: '103.245.222.162',
npm ERR!   port: 443 }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\caltech\npm-debug.log
_
Tried disabling the firewall but did not solve the issue. No other antivirus/firewall other than windows.
Could someone help me out?

**Comment by jainanshul** [comment]
did you try `sudo npm install -g fs-ext`? Instead you could run `npm install` from `caltech-pedestrian-dataset-extractor` folder. I updated the README to add the missing `npm install` step.

**Comment by aditya23788** [comment]
Hi Anshul,

What are the npm and node versions you are using? I tried the steps you mentioned in the README but I am getting following error:

node caltech_pd.js 

/home/adi/caltech_images/caltech-pedestrian-dataset-extractor/caltech_pd.js:2
let fs = require('fs-ext');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

My current setup has:
/usr/local/bin/node -v
v0.12.0

/usr/local/bin/npm -v
2.5.1

**Comment by jainanshul** [comment]
```
node -v
v4.2.1

npm -v
2.14.7

```

**Comment by manikandtan-ck** [comment]
on running npm install I get error while compiling fs-ext.
Attaching error log.
[output.txt](https://github.com/jainanshul/caltech-pedestrian-dataset-extractor/files/239322/output.txt)
This seemed to me like an issue with fs-ext. Is this reproducible by someone else?

**Comment by jainanshul** [comment]
It seems like you are trying this on windows. I have only tested on OSX and Ubuntu so far.

**Comment by manikandtan-ck** [comment]
Yes I am. Do you have any suggestions on how to fix this?

**Comment by jainanshul** [comment]
Not really, search online on issues to install fs-ext on windows.
